<?php

namespace Weather\SensorBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SensorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorTypeRepository extends EntityRepository
{
}
