<?php

namespace Weather\SensorBundle\Entity\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends EntityRepository
{
    /**
     * Retrieve all the connected sensors with only their (TODO:last) measure.
     */
    public function getSensorsWithLastMeasures()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->leftJoin('s.measures', 'm')
            ->addSelect('m')
            ->orderBy('m.date', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
