version: '2'

services:
  apache:
    image: akeneo/apache-php
    depends_on:
      - mysql
    environment:
      COMPOSER_HOME: /home/docker/.composer
      PHP_IDE_CONFIG: 'serverName=pim-ce-cli'
    user: docker
    ports:
      - 8087:80
    volumes:
      - ./:/srv/meteo
      - ~/.ssh/:/home/docker/.ssh
      - ~/.composer:/home/docker/.composer
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /srv/meteo
    networks:
      - meteo

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Goh8mae5
      MYSQL_DATABASE: meteo
    volumes:
      - /var/lib/mysql57:/var/lib/mysql
      - ~/Downloads:/home/root/Downloads
    ports:
      - '3306:3306'
    networks:
      - meteo

networks:
  meteo: ~
