<?php

namespace AppBundle\Repository;

/**
 * MeasureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
