<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Sensor;

/**
 * MeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureRepository extends EntityRepository
{
    public function getLastMeasureForSensor(Sensor $sensor)
    {
        $qb =  $this->createQueryBuilder('m');

        return $qb->leftJoin('m.sensor', 's')
                ->where('s = :sensor')
                ->orderBy('m.id', 'DESC')
                ->setParameter('sensor', $sensor)
                ->setMaxResults(1)
                ->getQuery()->getSingleResult()
            ;
    }
}
