<?php

namespace AppBundle\Repository;

/**
 * SensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorRepository extends \Doctrine\ORM\EntityRepository
{
}
