Weather\SensorBundle\Entity\Measure:
    type: entity
    table: null
    repositoryClass: Weather\SensorBundle\Entity\Repository\MeasureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        value:
            type: float
    manyToOne:
        sensor:
            targetEntity: Sensor
            inversedBy: measures
            joinColumn:
               name: sensor_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
