Weather\SensorBundle\Entity\Sensor:
    type: entity
    table: null
    repositoryClass: Weather\SensorBundle\Entity\Repository\SensorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        created:
            type: datetime
        lastSeen:
            type: datetime
            nullable: true
        connected:
            type: boolean
        rom:
            type: string
            length: 17
    manyToOne:
        type:
            targetEntity: SensorType
            inversedBy: sensors
            joinColumn:
               name: sensor_id
               referencedColumnName: id
    oneToMany:
        measures:
            targetEntity: Measure
            mappedBy: sensor
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
