services:
   app_bundle.twig.diff:
        class: AppBundle\Twig\AppExtension
        tags:
           - { name: twig.extension }

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
   shader:
       class: AppBundle\Color\Shader
       arguments:
          - '%min_temperature%'
          - '%max_temperature%'
          - '%cold_color%'
          - '%hot_color%'
