services:
   app_bundle.twig.diff:
        class: AppBundle\Twig\AppExtension
        tags:
           - { name: twig.extension }

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
   shader:
       class: AppBundle\Color\Shader
       arguments:
          - '%min_temp%'
          - '%max_temp%'
          - [32, 175, 204 ]
          - [239, 75, 43 ]