AppBundle\Entity\MeasureType:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MeasureTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        unit:
            type: string
            length: 255
    lifecycleCallbacks: {  }
