AppBundle\Entity\Measure:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MeasureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: float
        date:
            type: datetime
    manyToOne:
        measureType:
          targetEntity: AppBundle\Entity\MeasureType
          joinColumn:
            name: measure_type_id
            referencedColumnName: id
lifecycleCallbacks: {  }
