AppBundle\Entity\Sensor:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SensorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    manyToMany:
        supportedMeasureTypes:
            targetEntity: AppBundle\Entity\MeasureType
            joinTable:
                name: sensor_measur_types
                joinColumns:
                    sensor_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    measure_type_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
