App\Entity\Sensor:
    type: entity
    table: null
    repositoryClass: App\Repository\SensorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        supportedMeasure:
            type: smallint
            length: 1
    lifecycleCallbacks: {  }
